context:
  name: hatch-cython
  version: "0.6.0rc0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/joshua-auchincloss/${{ name|lower }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f6e451fb82754621d2229c1b7785937f279487621ff93150163c1bb319331a82
  patches:
    - fix#67.patch

build:
  script: ${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - cython
    - hatch
    - hatchling
    - setuptools
    - typing_extensions

tests:
  - script:
      # Tie the c++ command to actual c++ compiler (e.g. clang++ on macOS)
      - if: unix
        then:
          - ln -s $CXX_FOR_BUILD $PREFIX/bin/c++
      - c++ --version
      - pytest tests/ -v
    files:
      source:
          - tests/
          - test_libraries/
    requirements:
      run:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - if: osx
          then: cctools
        - llvm-openmp
        - python ${{ python_min }}.*
        - pytest
        - toml
        - numpy

about:
  homepage: https://github.com/joshua-auchincloss/hatch-cython/
  summary: Cython build hooks for hatch
  license: MIT
  license_file: LICENSE.txt
  repository: https://github.com/joshua-auchincloss/hatch-cython/

extra:
  recipe-maintainers:
    - munechika-koyo
