context:
  name: jumanji
  version: "1.1.0"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jumanji-${{ version }}.tar.gz
  sha256: 1baa7655bb59060f2435531e449baf2c24e7481ee02725bb34c05a722ac44b57
  patches:
    - relax-matplotlib-pin.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - chex >=0.1.3
    - dm-env >=1.5
    - gymnasium >=1.0
    - huggingface_hub
    - jax >=0.2.26,<0.4.36
    - matplotlib-base
    - numpy
    - pillow >=9.0.0
    - typing_extensions >=4.0.0

tests:
  - python:
      imports:
        - jumanji
      pip_check: true

about:
  summary: A diverse suite of scalable reinforcement learning environments in JAX
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/instadeepai/jumanji/

extra:
  recipe-maintainers:
    - Tobias-Fischer
