schema_version: 1

context:
  name: afni
  version: 25.0.00

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/afni/afni/archive/refs/tags/AFNI_${{ version }}.tar.gz
    sha256: e94f7f36821be42f202d0cb9e132087bd9e36b5cfb63f411e3b5399998739192
    patches:
      - Makefile.patch

build:
  number: 2
  skip: not linux

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - make
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
  host:
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
    - libexpat
    - expat
    - python
    - setuptools
    - numpy
    - scipy
    - glib
    - matplotlib-base
    - qhull
    - openmotif-dev
    - libgl-devel
    - xorg-libxpm
    - xorg-libxi
    - libglu
    - zlib
  run:
    - python

tests:
  - script:
      - set -xe
      - 1deval -help
      - 1dmatcalc -help
      - 1dplot -help
      - 1dtranspose -help
      - 24swap -help
      - 2dImReg -help
      - 2swap -help
      - 3dANOVA -help
      - 3dANOVA2 -help
      - 3dANOVA3 -help
      - 3dDeconvolve -help
      - 3dFriedman -help
      - 3dIntracranial -help
      - 3dKruskalWallis -help
      - 3dMannWhitney -help
      - 3dNLfim -help
      - 3dNotes -help
      - 3dROIstats -help
      - 3dRegAna -help
      - 3dStatClust -help
      - 3dTSgen -help
      - 3dTcat -help
      - 3dTsmooth -help
      - 3dTstat -help
      - 3dWilcoxon -help
      - 3daxialize -help
      - 3dbucket -help
      - 3dcalc -help
      - 3dclust -help
      - 3dfractionize -help
      - 3dhistog -help
      - 3dinfo -help
      - 3dmaskave -help
      - 3dmaskdump -help
      - 3dmerge -help
      - 3dnewid -help
      - 3dnvals -help
      - 3dpc -help
      - 3drefit -help
      - 3drotate -help
      - 3dvolreg -help
      - 4swap -help
      - RSFgen -help
      - adwarp -help
      - afni -help
      - byteorder -help
      - ccalc -help
      - cdf -help
      - count -help
      - count_afni -help
      - fim2 -help
      - float_scan -help
      - from3d -help
      - imand -help
      - imaver -help
      - imcalc -help
      - imdump -help
      - immask -help
      - imreg -help
      - imrotate -help
      - imstack -help
      - imstat -help
      - imupsam -help
      - nsize -help
      - plugout_ijk -help
      - plugout_tt -help
      - plugout_tta -help
      - sfim -help
      - tfim -help
      - to3d -help
      - waver -help
      - test -e ${PREFIX}/include/coxplot.h
      - test -e ${PREFIX}/include/niml.h
      - test -e ${PREFIX}/lib/libmri.so
      - test -e ${PREFIX}/lib/libf2c.so

about:
  homepage: https://github.com/afni/afni
  summary: A suite of programs for looking at and analyzing MRI brain images.
  description: AFNI (Analysis of Functional NeuroImages) is a suite of programs for looking at and analyzing MRI brain images at all stages of analysis (planning, setting up acquisition, preprocessing, analysis, quality control and statistical analysis).
  license: NIST-PD
  license_file: LICENSE.txt
  repository: https://github.com/afni/afni
  documentation: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/

extra:
  recipe-maintainers:
    - martin-g
