context:
  version: 0.1.4

package:
  name: libsvg
  version: ${{ version }}

source:
  url: https://cairographics.org/snapshots/libsvg-${{ version }}.tar.gz
  sha256: 4c3bf9292e676a72b12338691be64d0f38cd7f2ea5e8b67fbbf45f1ed404bc8f
  patches:
    - 0001-use-newer-autotools.patch
    - 0002-Fix-undefined-symbol-png_set_gray_1_2_4_to_8.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - libjpeg-turbo
    - libtool
    - libpng
    - libxml2 =2.13
    - zlib

tests:
  - script:
      - test -f ${PREFIX}/lib/libsvg${SHLIB_EXT}

about:
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: SVG rendering library using Cairo
  homepage: https://cairographics.org/

extra:
  recipe-maintainers:
    - danielnachun
