context:
  name: love2d
  version: 11.5
  build: ${{ 100 if variant == "latest" else 0 }}
  string_prefix: ${{ "luajit" if variant == "luajit" else "lua5_" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/love2d/love/archive/refs/tags/${{ version }}.tar.gz
    sha256: 6f55c265be5e03696c4770150c4388f5cffbdb3727606724cf88332baab429f7
    patches:
      - patches/0001-increase-minimum-cmake-version.patch
      - patches/0002-allow-using-cmake-on-windows.patch
      - patches/0003-install-binaries-in-right-locations.patch
      - patches/0004-find-correct-openal-library-on-windows.patch
      - patches/0005-fix-ssize_t-usage.patch
      - patches/0006-use-lua51-to-find-luajit-on-windows.patch

build:
  number: ${{ build|int }}
  string: ${{ string_prefix }}_h${{ hash }}_${{ build }}
  skip: 
    # Skip lua51 on windows because lua51 is not available on windows
    - variant == "lua51" and win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - freetype
    - libmodplug
    - openal-soft
    - sdl2
    - libtheora
    - libvorbis
    - zlib
    - libogg
    - mpg123
    - if: variant == "latest"
      then: 
        - lua
    - if: variant == "lua51"
      then: 
        - lua 5.1.*
    - if: variant == "luajit"
      then: 
        - luajit-openresty
    - if: linux
      then:
        - libgl-devel
        - libglx-devel
  run_exports: 
    - ${{ pin_subpackage(name) }}

tests:
  - package_contents:
      lib:
        - love
      bin:
        - love
        - if: win
          then: lovec
  - script:
      - ${{ "lovec" if win else "love" }} --version

about:
  homepage: https://love2d.org/
  repository: https://github.com/love2d/love
  documentation: https://love2d.org/wiki/Main_Page
  license: Zlib
  license_file: license.txt
  summary: LÖVE is an awesome framework you can use to make 2D games in Lua.
  description: |
    love2d (or LÖVE) is a lightweight, open-source framework for making 2D games in Lua. It provides cross-platform support and includes built-in modules for graphics, audio, physics, and input handling. Designed for rapid development, LÖVE is easy to use and ideal for prototyping and hobby projects.

extra:
  recipe-maintainers:
    - baszalmstra
    - tdejager
