context:
  name: libmodplug
  version: "0.8.8.5"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://downloads.sourceforge.net/project/modplug-xmms/${{ name }}/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 77462d12ee99476c8645cb5511363e3906b88b33a6b54362b4dbc0f39aa2daad
  patches: 
  - 0001-fix-non-const-stack-alloc.patch
  - if: win
    then: 0002-fix-dll-export-mismatch.patch
  - if: unix
    then: 0003-fix-use-gcc-visibility-attributes.patch

build:
  number: 2

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports: 
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - modplug
      include:
        - libmodplug/it_defs.h
        - libmodplug/modplug.h
        - libmodplug/sndfile.h
        - libmodplug/stdafx.h

about:
  homepage: http://modplug-xmms.sf.net/
  summary: libmodplug is an open-source library for playing MOD audio files
  description: |
    libmodplug is an open-source library for playing MOD audio files (and related tracker formats like S3M, IT, XM). It’s often used in games and multimedia apps to add music playback without needing external dependencies.
  license: BSD-3-Clause OR LicenseRef-Public-Domain
  license_file: COPYING
  repository: https://sourceforge.net/projects/modplug-xmms/

extra:
  recipe-maintainers:
    - baszalmstra
