schema_version: 1

context:
  name: rapidsim
  version: 1.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/gcowan/RapidSim/archive/v${{ version }}.tar.gz
  sha256: 14d8043fd40805f3bc144c4e35846392de535bbfee842ea2d1ec9232c7b0c585
  patches:
    - 0001-Update-CMakeLists.txt.patch
    - 0002-Fix-linking-to-evtgen-on-macOS.patch
    - 0003-Remove-Werror-for-CMAKE_CXX_FLAGS.patch

build:
  number: 22
  skip: win
  python:
    skip_pyc_compilation:
      - "*/utils/compareParts.py"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - sed
  host:
    - root_base
    - evtgen

tests:
  - script:
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/B2Kee 1000 1
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/B2Kee 100000
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/Bs2Jpsiphi 100000
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/Bd2D0rho0 100000
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/Bs2D0Kpi 10000
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/D02Kpi 100000
      - RapidSim.exe ${RAPIDSIM_ROOT}/validation/Lb2chicpK 100000
      - mkdir plots
      - "root -b -q -l \"${RAPIDSIM_ROOT}/validation/compareHistograms.C(\\\"B2Kee\\\")\""
      - "root -b -q -l \"${RAPIDSIM_ROOT}/validation/compareHistograms.C(\\\"Bs2Jpsiphi\\\")\""
      - "root -b -q -l \"${RAPIDSIM_ROOT}/validation/compareHistograms.C(\\\"Bd2D0rho0\\\")\""
      - "root -b -q -l \"${RAPIDSIM_ROOT}/validation/compareHistograms.C(\\\"Bs2D0Kpi\\\")\""
      - "root -b -q -l \"${RAPIDSIM_ROOT}/validation/compareHistograms.C(\\\"D02Kpi\\\")\""

about:
  # Linking to EvtGen forces RapidSim to be relicensed under GPL
  license: MIT AND GPL-3.0-or-later
  license_file: Licence.md
  summary: A fast Monte Carlo generator for simulation of heavy-quark hadron decays
  description: |
    RapidSim is a fast Monte Carlo generator for simulation of heavy-quark hadron decays.
    It can be useful for generating background or toy data sets for acceptance studies.

    * It uses [`TGenPhaseSpace`](https://root.cern.ch/doc/master/classTGenPhaseSpace.html) to generate b/c quark hadron decays.
    * [FONLL](http://cacciari.web.cern.ch/cacciari/fonll/) is used to give the b/c the correct production kinematics for the LHC.
    * The daughter particle momenta are smeared correctly using user-defined resolutions.
    * Cuts can be made on daughter particle properties (pT, eta, etc).
    * Particle mass hypotheses can be swapped to investigate effect of mis-identification.

    A more detailed description can be found here https://arxiv.org/abs/1612.07489
  homepage: https://github.com/gcowan/RapidSim
  repository: https://github.com/gcowan/RapidSim
  documentation: https://github.com/gcowan/RapidSim

extra:
  recipe-maintainers:
    - chrisburr
