context:
  name: libjaylink
  version: "0.4.0"
  build_num: 1
  so_version: "0.2.1"
  major_so_version: "0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.zapb.de/libjaylink/libjaylink/-/archive/${{ version }}/libjaylink-${{ version }}.tar.gz
  sha256: 5557d623934a4bbc053c11f9a181375d7abeb76af910696d9e3d9b1de3bf6987
  patches:
    - if: win
      then:
        # It would be great to upstream these patches
        - patches/add-jaylink.def.patch
        - patches/add-jaylink.lib-meson.build.patch
        - patches/enable-dynamic-library.patch
        - patches/fix-types-discovery_tcp.c.patch
        - patches/fix-types-discovery_usb.c.patch
        - patches/fix-types-fileio.c.patch
        - patches/fix-types-socket.c.patch
        - patches/fix-types-strutil.c.patch
        - patches/fix-types-transport_tcp.c.patch
        - patches/fix-types-transport_usb.c.patch
        - patches/fix-uninitialized.patch

build:
  number: ${{ build_num }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson >=1.1.0
    - ninja
    - pkg-config
    - if: win
      then:
        - m2w64-binutils
  host:
    - libusb
  run_exports:
    # This may be too stringent as API (i.e. 0.4.0) differs from ABI (i.e. 0.2.1)
    - ${{ pin_subpackage('libjaylink', upper_bound='x.x') }}

tests:
  - package_contents:
      files:
        - if: unix
          then:
            - lib/pkgconfig/libjaylink.pc
        - if: win
          then:
            - Library/lib/pkgconfig/libjaylink.pc
            - Library/lib/libjaylink.dll.a
            - Library/lib/libjaylink-${{ major_so_version }}.dll.a
      include:
        - libjaylink/libjaylink.h
        - libjaylink/version.h
      lib:
        - if: linux
          then:
            - libjaylink.so
            - libjaylink.so.${{ so_version }}
            - libjaylink.so.${{ major_so_version }}
        - if: osx
          then:
            - libjaylink.dylib
            - libjaylink.${{ major_so_version }}.dylib
        - if: win
          then:
            - jaylink.lib
      bin:
        - if: win
          then:
            - jaylink.dll
            - jaylink-${{ major_so_version }}.dll
            - libjaylink.dll
            - libjaylink-${{ major_so_version }}.dll
  - script:
      - if: win
        then:
          - python helpers\\verify_dll_def.py %PREFIX%\\Library\\bin\\libjaylink-${{ major_so_version }}.dll libjaylink\\jaylink.def
          - python helpers\\verify_dll_def.py %PREFIX%\\Library\\bin\\libjaylink.dll libjaylink\\jaylink.def
        else:
          - echo "Only windows is THAT high-maintenance!"
    files:
      recipe:
        - if: win
          then:
            - helpers/verify_dll_def.py
      source:
        - if: win
          then:
            - libjaylink/jaylink.def
    requirements:
      run:
        - if: win
          then:
            - m2w64-binutils
            - python

about:
  homepage: https://gitlab.zapb.de/libjaylink/libjaylink
  summary: 'libjaylink is a shared library written in C to access SEGGER J-Link.'
  description: |
    libjaylink is a shared library written in C to access SEGGER J-Link and
    compatible devices.
  license: GPL-2.0-or-later
  license_file: COPYING
  repository: https://gitlab.zapb.de/libjaylink/libjaylink

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: libjaylink
