# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.27.2

package:
  name: sqlalchemy-oso
  version: ${{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/sqlalchemy-v${{ version }}.tar.gz
  sha256: 18708bfd5cb74efc04d7191ea4247cec0182a52169da511f8059861c58116f20
  patches:
    # TODO: remove after https://github.com/osohq/oso/issues/1746
    - 0000-relax-packaging-pin.patch

build:
  number: 2
  noarch: python
  script:
    - cd languages/python/sqlalchemy-oso
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - oso >=0.27.0,<0.28.0
    - packaging >=21.3
    - python >=${{ python_min }}
    - sqlalchemy >=1.3.17,<3.0

tests:
  - python:
      imports: sqlalchemy_oso
      python_version: ${{ python_min }}.*
      pip_check: true
  - files:
      source:
        - languages/python/sqlalchemy-oso/tests/
    requirements:
      run:
        - flask <2.2
        - flask-sqlalchemy <3.0
        - pytest-cov
        - werkzeug ==2.2.2
        - python ${{ python_min }}
    script:
      - cd languages/python/sqlalchemy-oso
      - coverage run --source sqlalchemy_oso --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=75

about:
  summary: sqlalchemy-oso the SqlAlchemy integration for oso, the batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/osohq/oso/tree/main/languages/python/sqlalchemy-oso
  repository: https://github.com/osohq/oso
  documentation: https://docs.osohq.com/python/reference/api/sqlalchemy.html

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
