context:
  name: espsim
  version: 1.0.0
  git_version: 1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hesther/espsim/archive/refs/tags/v${{ git_version }}.tar.gz
  sha256: b381eae851e22d357ed25effe9dc80587fafc6c6cc7159863da9733292a6aabd
  patches:
    # The tagged version upstream did not update the setup.py version to 1.0.0.
    - setup-py.patch

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - rdkit
    - numpy
    - scipy
    - psi4
    - resp

tests:
  - python:
      imports:
        - espsim
      python_version: ${{ python_min }}.*
      pip_check: false  # cuz of https://github.com/conda-forge/qcelemental-feedstock/issues/54
  - files:
      source:
        - scripts/
    requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python scripts/test_imports.py
      - python scripts/test_esp_function.py
      - python scripts/test_embedalignscore.py

about:
  summary: Scoring of shape and ESP similarity with RDKit
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/hesther/espsim

extra:
  recipe-maintainers:
    - hesther
    - hadim
