schema_version: 1

context:
  version: 6.10

package:
  name: ragel
  version: ${{ version }}

source:
  url: https://www.colm.net/files/ragel/ragel-${{ version }}.tar.gz
  sha256: 5f156edb65d20b856d638dd9ee2dfb43285914d9aa2b6ec779dac0270cd56c3f
  patches:
    - patches/0001-Fix-undeclared-setiosflags-function.patch

build:
  number: 1003
  skip: win
  script: build.sh

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - make
    - autoconf
    - automake
    - libtool

tests:
  - requirements:
      run:
        - ${{ compiler("c") }}
    script: run_test.sh

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: Ragel State Machine Compiler
  description: |
    Ragel provides a very flexible interface to the host language that attempts
    to place minimal restrictions on how the generated code is integrated into
    the application. The generated code has no dependencies.
  homepage: https://www.colm.net/open-source/ragel/

extra:
  recipe-maintainers:
    - rmax
