context:
  name: cellxgene-census
  version: "1.17.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cellxgene_census-${{ version }}.tar.gz
  sha256: 934f55dbc1124d8929e440362af204c6a09668587b26dbfeefe17d8dce0b6e9d
  patches:
    - fix-test-open.patch

build:
  number: 0
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - tiledbsoma-py >=1.15.3
    - anndata
    - numpy >=1.23
    - requests
    - typing_extensions
    - s3fs >=2021.06.1
    - tiledb-py

tests:
  - python:
      imports:
        - cellxgene_census
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
        - requests-mock
        - datasets
        - proxy-py
    files:
      source:
        - tests/
        - pyproject.toml
    script: |
      # NOTE: we only run a subset of the full test suite to make the build faster
      # while still ensuring that the package is working correctly.
      pytest -vvv tests/test_open.py tests/test_util.py

      # Print the version for debugging purposes
      python -c "import cellxgene_census; print(cellxgene_census.__version__)"

about:
  summary: API to facilitate the use of the CZ CELLxGENE Discover Census.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chanzuckerberg/cellxgene-census/

extra:
  recipe-maintainers:
    - hadim
    - jdblischak
