schema_version: 1

context:
  name: createrepo_c
  version: 1.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/rpm-software-management/createrepo_c/archive/${{ version }}/createrepo_c-${{ version }}.tar.gz
  sha256: 5252911bb5ab0732922e298348a94f0e348e0891935ff0876042ac1bd8c5eeed
  patches:
    - 438.patch
    - 0001-Fix-includes.patch

build:
  number: 1
  skip: win or osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
    - cmake
    - pkg-config
  host:
    - python
    - zchunk
    - libcurl
    - openssl
    - xz
    - libmagic
    - sqlite
    - libxml2
    - glib
    - bzip2
    - rpm-tools
    - drpm
    - zlib
    - libmodulemd
    # Used for running tests
    - nose
    - doxygen
  run:
    - python
    # https://abi-laboratory.pro/index.php?view=timeline&l=rpm
    - ${{ pin_compatible('rpm-tools', upper_bound="x.x") }}
    - ${{ pin_compatible('libmodulemd', upper_bound="x") }}

tests:
  - script:
      - createrepo_c --help

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: C implementation of createrepo
  description: |
    Createrepo_c is a C implementation of the classical [Createrepo](http://createrepo.baseurl.org/)
    tool and simultaneously a C library for manipulation with a repodata.
    Createrepo_c provides Python bindings too, so could be easily used instead
    of [yum library](http://yum.baseurl.org/) for certain kinds of
    manipulations with repodata.
  homepage: http://rpm-software-management.github.io/createrepo_c/
  repository: https://github.com/rpm-software-management/createrepo_c
  documentation: https://github.com/rpm-software-management/createrepo_c/wiki

extra:
  recipe-maintainers:
    - chrisburr
