context:
  name: "fastjet-cxx"
  version: "3.5.0"

recipe:
  # Have top level name be unique from any outputs
  # c.f. https://github.com/conda-forge/conda-forge.github.io/blob/abfc33db28c35e9a8f6b719d0021768f0d5d06be/docs/maintainer/knowledge_base.md?plain=1#L1749
  name: ${{ name }}-split
  version: ${{ version }}

source:
  url: https://gitlab.com/fastjet/fastjet/-/archive/fastjet-${{ version }}/fastjet-fastjet-${{ version }}.tar.gz
  sha256: 67c314aec7899f098c9ec8fb2ca0c46a3b7700cbb756278ab4a6a02f34ba1dc9
  patches: enable-python-binding-only-build.patch

build:
  number: 3
  skip: win

outputs:
  - package:
      name: ${{ name }}

    build:
      script:
        - cmake "${CMAKE_ARGS}" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DFASTJET_ENABLE_ALLCXXPLUGINS=ON -DFASTJET_ENABLE_CGAL=ON -DFASTJET_USE_INSTALLED_SISCONE=ON -DFASTJET_ENABLE_PYTHON=OFF -S . -B build
        - cmake -LH build
        - cmake --build build --parallel="${CPU_COUNT}"
        - cmake --install build

    requirements:
      run_exports:
        - ${{ pin_subpackage('fastjet-cxx', upper_bound='x.x') }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - if: unix
          then: make
        - cgal
        - if: build_platform != target_platform
          then:
            - gmp
            - mpfr
            - siscone
      host:
        - gmp
        - mpfr
        - siscone
      run:
        - siscone

    tests:
      - package_contents:
          include:
            - fastjet/*.h
            - fastjet/*.hh
            - fastjet/internal/*.hh
            - fastjet/tools/*.hh
          lib:
            - fastjet
            - fastjetplugins
            - fastjettools
          bin:
            - fastjet-config
      - script:
          - fastjet-config --help
          - fastjet-config --version
          - fastjet-config --prefix
          - fastjet-config --cxxflags
          - fastjet-config --libs
          - fastjet-config --list-plugins
          - fastjet-config --libs --plugins
          - fastjet-config --config

          - cd example/
          - $CXX fastjet_example.cc -o fastjet_example $CXXFLAGS $LDFLAGS -lfastjet
          - ./fastjet_example < data/single-event.dat
          - $CXX fastjet_areas.cc -o fastjet_areas $CXXFLAGS $LDFLAGS -lfastjet
          - ./fastjet_areas < data/single-event.dat
          - $CXX 01-basic.cc -o 01-basic $CXXFLAGS $LDFLAGS -lfastjet
          - ./01-basic < data/single-event.dat
          - $CXX 02-jetdef.cc -o 02-jetdef $CXXFLAGS $LDFLAGS -lfastjet
          - ./02-jetdef < data/single-event.dat
          - $CXX 03-plugin.cc -o 03-plugin $CXXFLAGS $LDFLAGS -lfastjet -lfastjetplugins
          - ./03-plugin < data/single-event.dat
          - rm ./03-plugin
          - $CXX 03-plugin.cc -o 03-plugin $CXXFLAGS $LDFLAGS $(fastjet-config --libs --plugins)
          - ./03-plugin < data/single-event.dat
          - $CXX 04-constituents.cc -o 04-constituents $CXXFLAGS $LDFLAGS -lfastjet
          - ./04-constituents < data/single-event.dat
          - $CXX 05-eplus_eminus.cc -o 05-eplus_eminus $CXXFLAGS $LDFLAGS -lfastjet
          - ./05-eplus_eminus < data/single-ee-event.dat
          - $CXX 06-area.cc -o 06-area $CXXFLAGS $LDFLAGS -lfastjet
          - ./06-area < data/single-event.dat
          - $CXX 07-subtraction.cc -o 07-subtraction $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
          - ./07-subtraction < data/Pythia-Zp2jets-lhc-pileup-1ev.dat
          - $CXX 08-selector.cc -o 08-selector $CXXFLAGS $LDFLAGS -lfastjet
          - ./08-selector < data/single-event.dat
          - $CXX 09-user_info.cc -o 09-user_info $CXXFLAGS $LDFLAGS -lfastjet
          - ./09-user_info < data/Pythia-dijet-ptmin100-lhc-pileup-1ev.dat
          - $CXX 10-subjets.cc -o 10-subjets $CXXFLAGS $LDFLAGS -lfastjet
          - ./10-subjets < data/single-event.dat
          - $CXX 11-filter.cc -o 11-filter $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
          - ./11-filter < data/single-event.dat
          - $CXX 12-boosted_higgs.cc -o 12-boosted_higgs $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
          - ./12-boosted_higgs < data/HZ-event-Hmass115.dat
          - $CXX 13-boosted_top.cc -o 13-boosted_top $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
          - ./13-boosted_top < data/boosted_top_event.dat
          - $CXX 14-groomers.cc -o 14-groomers $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
          - ./14-groomers < data/boosted_top_event.dat

        files:
          source:
            - example/fastjet_example.cc
            - example/fastjet_areas.cc
            - example/01-basic.cc
            - example/02-jetdef.cc
            - example/03-plugin.cc
            - example/04-constituents.cc
            - example/05-eplus_eminus.cc
            - example/06-area.cc
            - example/07-subtraction.cc
            - example/08-selector.cc
            - example/09-user_info.cc
            - example/10-subjets.cc
            - example/11-filter.cc
            - example/12-boosted_higgs.cc
            - example/13-boosted_top.cc
            - example/14-groomers.cc
            - example/data/single-event.dat
            - example/data/single-ee-event.dat
            - example/data/Pythia-Zp2jets-lhc-pileup-1ev.dat
            - example/data/Pythia-dijet-ptmin100-lhc-pileup-1ev.dat
            - example/data/HZ-event-Hmass115.dat
            - example/data/boosted_top_event.dat
        requirements:
          run:
            - ${{ compiler('cxx') }}

  - package:
      name: ${{ name }}-python

    build:
      # clobber existing fastjet-config from fastjet-cxx
      # c.f. https://rattler.build/latest/build_options/#always-include-and-always-copy-files
      always_include_files:
        - bin/fastjet-config
      script:
        - cmake "${CMAKE_ARGS}" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DFASTJET_ENABLE_ALLCXXPLUGINS=ON -DFASTJET_ENABLE_CGAL=ON -DFASTJET_USE_INSTALLED_SISCONE=ON -DFASTJET_ENABLE_PYTHON=ON -DFASTJET_PYTHON_ONLY=ON -DFASTJET_USE_PYTHON_SITEARCH=ON -DFASTJET_PYTHON_PACKAGE_NAME="fastjet_cxx" -DPython_EXECUTABLE=${{ PYTHON }} -S . -B build
        - cmake -LH build
        - cmake --build build --parallel="${CPU_COUNT}"
        - cmake --install build

    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - swig
        - cmake
        - if: unix
          then: make
        - cgal
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - fastjet-cxx
      host:
        - python
        - fastjet-cxx
      run:
        - python
        - fastjet-cxx

    tests:
      - python:
          imports:
            - fastjet_cxx
          pip_check: true
          python_version: ${{ python }}
      - script:
          - fastjet-config --help
          - fastjet-config --version
          - fastjet-config --prefix
          - fastjet-config --cxxflags
          - fastjet-config --libs
          - fastjet-config --list-plugins
          - fastjet-config --libs --plugins
          - fastjet-config --config
          - fastjet-config --pythonpath

          - python -c "import fastjet_cxx as fj; jetdef=fj.JetDefinition(fj.antikt_algorithm, 0.4); jets=jetdef([fj.PtYPhiM(100.0, 0.1, 0.1),fj.PtYPhiM(100.0, 0.2, 0.2)]); print(jets[0])"

about:
  homepage: https://gitlab.com/fastjet/fastjet
  summary: 'FastJet: jet finding in pp and e+e- collisions'
  description: |
    FastJet is a software package for jet finding in pp and e+e- collisions.
    It includes fast native implementations of many sequential recombination
    clustering algorithms, plugins for access to a range of cone jet finders
    and tools for advanced jet manipulation.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  repository: https://gitlab.com/fastjet/fastjet
  documentation: https://fastjet.fr/

extra:
  feedstock-name: fastjet-cxx
  recipe-maintainers:
    - lgray
    - kratsg
    - matthewfeickert
