context:
  name: "delphes"
  version: "3.5.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/delphes/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 30a2536e0c8f47d633ecf3b4d51ec9924af54538e492470ad47b4ed34342f063
  patches:
    # Fixes builds for macOS
    # c.f. https://github.com/delphes/delphes/pull/128
    - Delphes-ClosestPair2D-fwdDeclaration.patch
    # c.f. https://github.com/delphes/delphes/commit/64de5a479b94beba357e73c926cdc6ee9114ceec
    - remove_binary_function.patch
    # c.f. https://github.com/delphes/delphes/pull/154
    - use-range-of-supported-cmake.patch

build:
  number: 5
  skip:
    - win
  script:
    # Make the examples location independent by removing the 'external/' prefix
    # in includes to instead use the installed versions
    - grep -r -l "external/" examples/ | xargs sed -i 's|external/||g'
    - CXXFLAGS="${CXXFLAGS}" cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=$PREFIX -DPYTHIA8_DATA=$(pythia8-config --datadir) -S . -B build
    - cmake build -LH
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
    - grep
    - sed
  host:
    - root_base
    - pythia8

tests:
  - script:
      # Running the 'DelphesXXX --help' commands results in exit code 1,
      # so check for existence instead.
      - test -f "${PREFIX}"/bin/DelphesHepMC2
      - test -f "${PREFIX}"/bin/DelphesHepMC3
      - test -f "${PREFIX}"/bin/DelphesLHEF
      - test -f "${PREFIX}"/bin/DelphesPythia8
      - test -f "${PREFIX}"/bin/DelphesROOT
      - test -f "${PREFIX}"/bin/DelphesSTDHEP

      # N.B.: MUST be http not https (unfortunately)
      - curl -LO http://cp3.irmp.ucl.ac.be/downloads/z_ee.hep.gz
      - gunzip z_ee.hep.gz
      - DelphesSTDHEP "${PREFIX}"/cards/delphes_card_CMS.tcl delphes_output.root z_ee.hep

      - # avoid lots of output to stdout
      - root -l -b -q "${PREFIX}"/examples/Example1.C'("delphes_output.root")' &> /dev/null
      - root -l -b -q "${PREFIX}"/examples/Example2.C'("delphes_output.root")'
      - root -l -b -q "${PREFIX}"/examples/Example3.C'("delphes_output.root")'
      - root -l -b -q "${PREFIX}"/examples/Example4.C'("delphes_output.root", "plots.root")'
      - root -l -b -q "${PREFIX}"/examples/Example5.C'("delphes_output.root")' &> /dev/null
      # FIXME: Example6.C is failing in CI but not locally
      # - root -l -b -q $PREFIX/examples/Example6.C'("delphes_output.root")'

    requirements:
      run:
        - ${{ compiler('cxx') }}
        - root_base
        - pythia8
        - gzip
        - curl
        - grep
        - sed

about:
  summary: 'A framework for fast simulation of a generic collider experiment'
  description: |
    Delphes is a C++ framework, performing a fast multipurpose detector
    response simulation. The simulation includes a tracking system, embedded
    into a magnetic field, calorimeters and a muon system. The framework is
    interfaced to standard file formats (e.g. Les Houches Event File or HepMC)
    and outputs observables such as isolated leptons, missing transverse energy
    and collection of jets which can be used for dedicated analyses.
    The simulation of the detector response takes into account the effect of
    magnetic field, the granularity of the calorimeters and sub-detector resolutions.
    Visualisation of the final state particles is also built-in using the
    corresponding ROOT library.
  license: GPL-3.0-or-later
  license_file: COPYING
  homepage: https://github.com/delphes/delphes
  documentation: https://cp3.irmp.ucl.ac.be/projects/delphes
  repository: https://github.com/delphes/delphes

extra:
  recipe-maintainers:
    - pavel-demin
    - matthewfeickert
    - kratsg
