schema_version: 1

context:
  version: 1.16.2

package:
  name: dbus
  version: ${{ version }}

source:
  url: http://dbus.freedesktop.org/releases/dbus/dbus-${{ version }}.tar.xz
  sha256: 0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2
  patches:
    - if: linux
      then:
        - patches/0001-Add-var-lib-dbus-machine-id-as-a-fallback.patch
        - patches/0002-Use-proc-sys-kernel-random-boot_id-as-last-resort-fa.patch
        - patches/0003-disable-fd-limit-tests-not-supported-in-docker.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - meson
  host:
    - glib
    - expat
    - zlib
  run_exports:
    - ${{ pin_subpackage('dbus') }}

tests:
  - script:
      - dbus-daemon --version
      - dbus-uuidgen

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Simple message bus system for applications to talk to one another
  description: |
    D-Bus is a message bus system, a simple way for applications
    to talk to one another. In addition to interprocess communication, D-Bus helps
    coordinate process lifecycle; it makes it simple and reliable to code a "single
    instance" application or daemon, and to launch applications and daemons on
    demand when their services are needed.
  homepage: http://www.freedesktop.org/wiki/Software/dbus/
  repository: git://anongit.freedesktop.org/dbus/dbus
  documentation: https://www.freedesktop.org/wiki/IntroductionToDBus/

extra:
  recipe-maintainers:
    - mingwandroid
    - ccordoba12
    - nehaljwani
    - ocefpaf
    - xhochy
