schema_version: 1

context:
  name: openlb
  version: 1.7r0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://zenodo.org/records/10684609/files/olb-${{ version }}.tgz
  sha256: a71a3d458680598340e391e108ffa8cfbdc8c8e5900b1f72a6191c878fbff06c
  patches:
    - openlb-makefile.patch

build:
  number: 1
  skip: win

requirements:
  build:
    - make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
  host:
    - zlib
    - tinyxml
  run:
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x') }}

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/lib/libolbcore${SHLIB_EXT}

about:
  license: GPL-2.0-only
  license_file: LICENSE
  summary: |
    An implementation of lattice Boltzmann methods that is general enough to address
    a vast range of transport problems, e.g. in computational fluid dynamics
  homepage: https://www.openlb.net/
  documentation: https://www.openlb.net/user-guide/

extra:
  recipe-maintainers:
    - martin-g

