context:
  name: cherab
  version: "1.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name|lower }}/core/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 39cd2d4e14546c472a44ebb5eef2a171797338b928ccb5eab902dcc7aa77b521
  patches:
    - numpy2.patch

build:
  script: ${{ PYTHON }} -m pip install --no-build-isolation --no-deps -vv .
  number: 2
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools
        - cython
        - numpy
        - raysect >=0.8.1,<0.9a0
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - raysect >=0.8.1,<0.9a0
  run:
    - python
    - scipy
    - matplotlib-base
  run_exports:
    - ${{ pin_subpackage("cherab", lower_bound="x.x.x", upper_bound="x.x.x") }}

tests:
  - python:
      imports:
        - cherab
        - cherab.core
        - cherab.generomak
        - cherab.openadas
        - cherab.tools
      pip_check: false

  - script:
      - if: unix
        then:
          - python -c "import cherab; print(cherab.__path__[0])" | xargs python -m unittest discover -v -s
      - if: win
        then:
          - python -c "import cherab; print(cherab.__path__[0])" | python -m unittest discover -v -s ?



about:
  homepage: https://www.cherab.info/
  summary: Cherab spectroscopy framework
  license: EUPL-1.1
  license_file: LICENCE.txt
  documentation: https://cherab.github.io/documentation/
  repository: https://github.com/cherab/core.git

extra:
  recipe-maintainers:
    - munechika-koyo
