schema_version: 1

context:
  name: yoda
  version: 2.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://yoda.hepforge.org/downloads?f=YODA-${{ version }}.tar.gz
  sha256: dc0c34fd77eda0bfd67a2a46d17f460b532527743e96853dd1a1f7964c696b6d
  file_name: YODA-${{ version }}.tar.gz
  # Can't apply patches here, see: https://github.com/prefix-dev/rattler-build/issues/1418
  # patches:
  #   - 0001-Fix-setting-rpath-when-installing-on-macOS.patch
  #   - 0002-Support-overriding-install_name_tool.patch
  #   - 0003-Do-not-link-against-libpython.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - make
    - autoconf
    - automake
    - libtool
    # Required due to https://github.com/prefix-dev/rattler-build/issues/1418
    - patch
    - tar
  host:
    - python
    - cython >=0.24
    - zlib
  run:
    - python
    - matplotlib-base

tests:
  - python:
      imports:
        - yoda
  - script:
      - root2yoda --help
      - yoda-config --help
      - yoda2root --help
      - yoda2yoda --help
      - yodacnv --help
      - yodadiff --help
      - yodaenvelope --help
      - yodals --help
      - yodamerge --help
      - yodaplot --help
      - yodascale --help
      - yodastack --help

about:
  license: GPL-3.0-only
  license_file: COPYING
  summary: Yet more Objects for Data Analysis
  description: |
    YODA is a small set of data analysis (specifically histogramming) classes
    being developed by MCnet members as a lightweight common system for MC
    event generator validation analyses, particularly as the core histogramming
    system in Rivet.


  homepage: https://yoda.hepforge.org/
  repository: https://gitlab.com/hepcedar/yoda/
  documentation: https://gitlab.com/hepcedar/yoda/

extra:
  recipe-maintainers:
    - chrisburr
    - conda-forge/hepmc3
