schema_version: 1

context:
  name: linetimer
  version: 0.1.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/linetimer-${{ version }}.tar.gz
  sha256: f9723860bbbeae05e4e1383b237e5b73f98c71b73e50dc8c2856a0580269752b
  patches:
    - readme.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    # - python ${{ python_min }}.*
    - pip
    - setuptools
  # run:
  #   - python >=${{ python_min }}

# tests:
#   - python:
#       imports:
#         - linetimer
#       pip_check: true
#       python_version: ${{ python_min }}.*

about:
  summary: A small Python class to quickly measure the time taken while executing a block of indented lines
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/justasb/linetimer

extra:
  recipe-maintainers:
    - synapticarbors
