context:
  name: deepsearch-glm
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/deepsearch_glm-${{ version }}.tar.gz
  sha256: e8dce88ac519a693c260f28bd3c4ec409811e65ade84fb508f6c6e37ca065e62
  patches:
    - fix-utfcpp.patch

build:
  number: 4
  skip: win
  script:
    content: python -m pip install . -vv --no-deps --no-build-isolation
    env:
      USE_SYSTEM_DEPS: "on"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}

    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - ${{ "make" if unix else "ninja" }}
    - pkg-config
  host:
    # build tools
    - python
    - poetry-core
    - pybind11 >=2.13.1
    - pip
    # libraries
    - fmt
    - cxxopts
    - nlohmann_json
    - loguru-cpp
    - utfcpp
    - fasttext-for-deepsearch-glm
    - json_schema_validator
    - pcre2
    - libsentencepiece
    - zlib
  run:
    - python
    - numpy
    - ${{ "pywin32 >=307" if win }}
    - docling-core >=2.0.0,<3.0.0
    - tabulate >=0.8.9
    - pandas >=1.5.1,<3.0.0
    - matplotlib-base >=3.7.1,<4.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - tqdm >=4.64.0,<5.0.0
    - rich >=13.7.0,<14.0.0
    - requests >=2.32.3,<3.0.0

tests:
  - python:
      imports:
        - deepsearch_glm
      pip_check: true

about:
  summary: Create fast graph language models from converted PDF documents for knowledge extraction and Q&A.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DS4SD/deepsearch-glm/

extra:
  recipe-maintainers:
    - hadim
