schema_version: 1

context:
  name: xgrammar
  version: "0.1.19"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/xgrammar-${{ version }}.tar.gz
  sha256: 75bf3e814283b1cbaee9252234c5d4081f0058d29b26d8984f1cdf031c99b775
  patches:
    - patches/001_remove_ninja_dep.patch

build:
  number: 0
  script:
    - if: unix
      then: |
        export CMAKE_BUILD_TYPE=Release
        export CXXFLAGS="$CXXFLAGS -isystem $PREFIX/include"
        if [[ $(uname) == "Linux" ]]; then
          export CXXFLAGS="$CXXFLAGS -Wno-dangling-reference"
        fi
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - scikit-build-core >=0.10.0
        - dlpack
        - pytest
        - nanobind
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - if: unix
      then:
        - make
  host:
    - python
    - scikit-build-core >=0.10.0
    - pip
    - dlpack
    - pytest
    - nanobind
  run:
    - python
    - numpy >=1.26.0
    - ninja
    - pydantic
    - sentencepiece
    - tiktoken
    - pytorch >=1.10.0
    - transformers >=4.38.0
    - if: linux and x86_64
      then: triton
    - if: osx and arm64
      then: mlx-lm

tests:
  - python:
      imports:
        - xgrammar
      pip_check: true

  - script:
      - python -m pytest tests/ -m "not hf_token_required"
    files:
      source:
        - tests/
    requirements:
      run:
        - ninja
        - protobuf
        - pytest
        - huggingface_hub
        - numpy >=1.26.0
        - pydantic
        - sentencepiece
        - tiktoken
        - pytorch >=1.10.0
        - transformers >=4.38.0

about:
  homepage: https://github.com/mlc-ai/xgrammar
  summary: XGrammar is an open-source library for efficient, flexible, and portable structured generation.
  license: Apache-2.0 AND BSD-4-Clause
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - zbowling
    - Ubospica
