context:
  name: MDRestraintsGenerator
  version: 0.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/MDRestraintsGenerator-${{ version }}.tar.gz
  sha256: 031e96539e9fae0048b501026f5d596e518693bf8f4ada3afc80e37c284e98d3
  patches:
    - fix-deps.patch

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - mdanalysis >1.0.0
    - numpy
    - scipy
    - matplotlib-base

tests:
  - python:
      imports:
        - MDRestraintsGenerator
      python_version: ${{ python_min }}.*

about:
  summary: Enabling the use of restraints in alchemical simulations
  license: LGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/IAlibay/MDRestraintsGenerator/

extra:
  recipe-maintainers:
    - hadim
