context:
  version: 0.2.21

package:
  name: colbert-ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/colbert-ai/colbert_ai-${{ version }}.tar.gz
    sha256: a8d6fdb4e2272f2b08ed37f8e5096072160d8415d1e40585751898b77e625bab
    patches:
      - 0000-patch-wrong-gitpython.patch  # https://github.com/stanford-futuredata/ColBERT/pull/388
      - 0001-remove-python-ninja.patch

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - bitarray
    - datasets
    - flask
    - gitpython
    - python-dotenv
    - ninja
    - scipy
    - tqdm
    - transformers
    - pytorch
    - ujson

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - colbert
      pip_check: true

about:
  homepage: https://github.com/stanford-futuredata/ColBERT
  summary: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
